### PR TITLE
Move all CSS to different component modules

### PR DESCRIPTION
**Pull request by nosoycesaros**
This PR creates CSS files for each component, in order to improve maintainability

image

It also creates a temporary demo page
image

### CODE REVIEW

**Comment by nikhilmwarrier** [comment]
That idea is awesome! I suppose we can distribute it in two edition: Complete and Modular. 
The complete version is for those who want to rapidly prototype and create pages. 
The modular one would be really useful for contributors and developers, and also those who want to reduce file size and choose only the components they want.
 I suppose we can branch them out or something?
 Anyway, let me know your final thoughts and anything you might've forgotten to add before I actually merge this PR.
 
PS: Modularity was always something I've been worried about. Your solution is pretty elegant. 
Also thanks for taking time out to contribute...

**Comment by nikhilmwarrier** [comment]
Also, we should group together similar and more commonly used components into the base CSS pack, just so to make it modular, but not overwhelming for beginner developers...

**Comment by nosoycesaros** [comment]
Different versions is a good idea, and commonly used component as well, i can think something like `fluid/base` and `fluid/extended` with more complex components

I think the PR is pretty simple, so feel free to merge it when you're ready.

**Comment by nikhilmwarrier** [comment]
OK! Let me create a new branch and I will merge! I am getting some more stuff ready and I will merge...

**Comment by cobrexus** [comment]
@nosoycesaros @nikhilmwarrier I think you should consider the following points before you make this change:

* Using multiple files is actually not a good idea, because it means more requests when loading the files via CDN. This requires more bandwidth, which is not optimal, and one request is preferred to several.

* Also, not many developers are familiar with SASS and it doesn't run natively in the browser, so this lib won't be useable over a CDN if you use a CSS preprocessor. It is preferable to go with vanilla CSS.

* [halfmoonui/halfmoon](../../../halfmoonui/halfmoon) which is the library this one [was inspired by](https://css-tricks.com/considerations-for-making-a-css-framework/#comment-1765403) uses a single `.min.css` and `.min.js` file over CDN, and one `.css`/`.js` file in development, since one request (or two) are better than many. One of the principles of that library is also to use vanilla CSS for the fastest runtime and wide browser support.

Just my thoughts, as I'm keen on becoming a contributor to this library and watch it grow! 😃

**Comment by nikhilmwarrier** [comment]
@AryanBeezadhur Thanks a lot... 
I too thought of that and decided to keep them as a single file. And I was inspired by Halfmoon in the first place : )  
Thanks for being here!

**Pull request closed without merging**
